#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
#

echo -e "Updating package list and installing Nginx.\n"
sudo apt-get update -y -qq && \
    sudo apt-get install nginx -y

echo -e "\nStarting Nginx service and configuring firewall.\n"

# Starting Nginx service
sudo service nginx start

# Allowing Nginx on firewall, if ufw is installed
if command -v ufw >/dev/null 2>&1; then
    sudo ufw allow 'Nginx HTTP'
fi

# Creating a new index.html file with "Hello World!"
echo "<html><body><h1>Hello World!</h1></body></html>" | sudo tee /var/www/html/index.html

# Restarting Nginx to apply changes
sudo service nginx restart

echo -e "\nConfiguration completed successfully. ✅\n"

