#!/usr/bin/env bash
# Script displaying "Best School" 10 times.
#  and before the last "Best School" display "Hi".

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
