#!/usr/bin/env bash
# Script displaying contents of current directory in list format.
#   Only displays part of the name after the first dash. 

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
